project_id = "zoomsxaoqkywdqpdtqnm"

[functions.alchemy-rpc]
verify_jwt = false

[functions.content-moderation]
verify_jwt = false

[functions.track-clip-event]
verify_jwt = false

[functions.livepeer-stream]
verify_jwt = false

[functions.ipfs-upload]
verify_jwt = false

[functions.process-scheduled-reveals]
verify_jwt = false

[functions.cleanup-deleted-collections]
verify_jwt = false
