project_id = "zoomsxaoqkywdqpdtqnm"

[functions.alchemy-rpc]
verify_jwt = false

[functions.content-moderation]
verify_jwt = false

[functions.track-clip-event]
verify_jwt = false

[functions.livepeer-stream]
verify_jwt = false

[functions.ipfs-upload]
verify_jwt = false

[functions.process-scheduled-reveals]
verify_jwt = false

[functions.cleanup-deleted-collections]
verify_jwt = false

[functions.webrtc-stream]
verify_jwt = false

[functions.rpc-proxy]
verify_jwt = false

[functions.fetch-nft-floor-prices]
verify_jwt = false

[functions.fetch-nfts]
verify_jwt = false

[functions.admin-users]
verify_jwt = true

[functions.track-volume]
verify_jwt = false

[functions.expire-bundles]
verify_jwt = false

[functions.draw-raffle-winners]
verify_jwt = false

[functions.get-streamer-wallet]
verify_jwt = false

[functions.resolve-streak-challenges]
verify_jwt = false
