// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fail-safe initialization for decentralized mode (no-db)
const isSupabaseConfigured = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.warn("[LilyPad] Supabase keys missing in .env. App is running in Decentralized Storage mode (Arweave only).");
}

const mockResponse = (data: any = null) => Promise.resolve({ data, error: null });

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : ({
    from: () => ({
      select: () => ({
        eq: () => ({
          single: () => mockResponse({ id: "offline" }),
          order: () => ({ range: () => mockResponse([]) }),
          maybeSingle: () => mockResponse(null)
        }),
        maybeSingle: () => mockResponse(null),
        order: () => ({ range: () => mockResponse([]) }),
        is: () => ({ in: () => ({ order: () => ({ range: () => mockResponse([]) }) }) })
      }),
      insert: () => ({ select: () => ({ single: () => mockResponse({ id: "offline" }) }) }),
      update: () => ({ eq: () => mockResponse(null) }),
      upsert: () => ({ select: () => ({ single: () => mockResponse(null) }) }),
      delete: () => ({ eq: () => ({ eq: () => mockResponse(null) }) }),
    }),
    storage: {
      from: () => ({
        upload: () => mockResponse({ path: "mock-path" }),
        list: () => mockResponse([]),
        remove: () => mockResponse([]),
        getPublicUrl: () => ({ data: { publicUrl: "" } }),
      })
    },
    rpc: () => mockResponse({ totalCollections: 0, liveNow: 0, nftsMinted: 0, totalVolume: 0 }),
    auth: {
      getUser: () => mockResponse({ user: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
      signOut: () => mockResponse(null),
    },
    channel: () => ({
      on: () => ({ subscribe: () => { } }),
      subscribe: () => { },
      unsubscribe: () => { }
    }),
    removeChannel: () => { },
    isOffline: true
  } as any);