// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fail-safe initialization for decentralized mode (no-db)
const isSupabaseConfigured = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.warn("[LilyPad] Supabase keys missing in .env. App is running in Decentralized Storage mode (Arweave only).");
}

const mockResponse = (data: any = null) => Promise.resolve({ data, error: null });

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : ({
    storage: {
      from: () => ({
        upload: () => mockResponse({ path: "mock-path" }),
        list: () => mockResponse([]),
        remove: () => mockResponse([]),
        getPublicUrl: () => ({ data: { publicUrl: "" } }),
      })
    },
    rpc: () => mockResponse({ totalCollections: 0, liveNow: 0, nftsMinted: 0, totalVolume: 0 }),
    auth: {
      getUser: () => mockResponse({ user: null }),
      getSession: () => mockResponse({ session: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
      signOut: () => mockResponse(null),
    },
    channel: function () {
      const self = {
        on: () => self,
        subscribe: () => self,
        unsubscribe: () => { },
        track: () => Promise.resolve(),
        presenceState: () => ({})
      };
      return self;
    },
    removeChannel: () => { },
    from: () => {
      const self = {
        select: () => self,
        eq: () => self,
        neq: () => self,
        lt: () => self,
        lte: () => self,
        gt: () => self,
        gte: () => self,
        ilike: () => self,
        order: () => self,
        limit: () => self,
        single: () => mockResponse({ id: "offline" }),
        maybeSingle: () => mockResponse(null),
        insert: () => self,
        update: () => self,
        upsert: () => self,
        delete: () => self,
        match: () => self, // Added match for better compatibility
        in: () => self,
        range: () => mockResponse([]),
        then: (resolve: any) => resolve(mockResponse([])) // Allow awaiting the chain
      };
      return self;
    },
    isOffline: true
  } as any);